"""Reference numerical implementation for the Butterfly research program."""

from .atlas import PeriodicComponent, periodic_components, ranked_recurrence_candidates
from .augmented_flip import (
    augmented_flip_system,
    integrate_flip_segment,
    rossler_hessian_action,
)
from .basins import (
    BasinPlaneManifest,
    evaluate_initial_condition,
    fit_uncertainty_exponent,
    initial_condition_grid,
)
from .boundary import OrderedTransitionBracket, infer_ordered_transition_bracket

from .candidates import CandidateSelection, select_low_score_with_neighbors
from .classify import (
    DynamicsClassification,
    DynamicsThresholds,
    OrbitLabel,
    PeriodClassification,
    RecurrenceCandidate,
    classify_fundamental_period,
    classify_with_lyapunov,
    closest_recurrence_candidate,
    combine_initial_conditions,
)
from .integrate import SolverConfig, Trajectory, integrate_trajectory
from .lyapunov import (
    LargestLyapunovResult,
    LyapunovConfig,
    LyapunovResult,
    largest_lyapunov_two_trajectory,
    lyapunov_block_estimates,
    lyapunov_spectrum,
)
from .models import (
    RosslerParameters,
    equilibrium_eigenvalues,
    rossler_equilibria,
    rossler_jacobian,
    rossler_rhs,
)
from .poincare import (
    PoincareCrossings,
    PoincareSection,
    barrio_rossler_section,
    collect_crossings,
    legacy_rossler_section,
)
from .return_map import (
    LowerSupportSlopeRobustnessResult,
    ReturnMapBranchResult,
    ReturnMapCoverageCensorResult,
    ReturnMapRobustnessResult,
    infer_lower_support_slope_robust,
    infer_return_map_branches,
    infer_return_map_branches_coverage_censored,
    infer_return_map_branches_robust,
)
from .saddle import (
    CensorAwarePIMRefinementResult,
    CensorAwarePIMStraddleResult,
    CaptureLifetimeResult,
    PIMRefinementResult,
    PIMStraddleResult,
    PIMLifetimeBatch,
    PIMTriple,
    SectionReturnResult,
    SprinklerResult,
    advance_pim_straddle,
    advance_censor_aware_pim_straddle,
    capture_lifetimes_on_section,
    cycle_crossing_distances,
    next_section_return,
    refine_censor_aware_pim_segment,
    refine_pim_segment,
    scrambled_sobol_section_states,
    section_return_map,
    sprinkler_survivors,
    survivor_return_pairs,
)
from .periodic import (
    MonodromyResult,
    PeriodicOrbitCorrection,
    UnitMultiplierCorrection,
    correct_periodic_orbit,
    correct_unit_multiplier_orbit,
    flow_monodromy,
)
from .scan import ScanManifest, execute_scan, run_scan
from .tiles import (
    TileSpec,
    aggregate_scan_tiles,
    execute_scan_tile,
    verify_completed_aggregate,
    verify_completed_tile,
)

__all__ = [
    "OrbitLabel",
    "OrderedTransitionBracket",
    "PeriodicComponent",
    "CandidateSelection",
    "BasinPlaneManifest",
    "DynamicsClassification",
    "DynamicsThresholds",
    "LyapunovConfig",
    "LyapunovResult",
    "MonodromyResult",
    "PeriodicOrbitCorrection",
    "UnitMultiplierCorrection",
    "LargestLyapunovResult",
    "PeriodClassification",
    "RecurrenceCandidate",
    "ReturnMapBranchResult",
    "ReturnMapCoverageCensorResult",
    "ReturnMapRobustnessResult",
    "LowerSupportSlopeRobustnessResult",
    "RosslerParameters",
    "PoincareCrossings",
    "PoincareSection",
    "SolverConfig",
    "SprinklerResult",
    "SectionReturnResult",
    "CaptureLifetimeResult",
    "CensorAwarePIMRefinementResult",
    "CensorAwarePIMStraddleResult",
    "PIMTriple",
    "PIMRefinementResult",
    "PIMStraddleResult",
    "PIMLifetimeBatch",
    "ScanManifest",
    "Trajectory",
    "TileSpec",
    "aggregate_scan_tiles",
    "augmented_flip_system",
    "barrio_rossler_section",
    "equilibrium_eigenvalues",
    "evaluate_initial_condition",
    "fit_uncertainty_exponent",
    "execute_scan",
    "execute_scan_tile",
    "flow_monodromy",
    "collect_crossings",
    "classify_fundamental_period",
    "classify_with_lyapunov",
    "combine_initial_conditions",
    "correct_periodic_orbit",
    "correct_unit_multiplier_orbit",
    "cycle_crossing_distances",
    "advance_pim_straddle",
    "advance_censor_aware_pim_straddle",
    "capture_lifetimes_on_section",
    "closest_recurrence_candidate",
    "integrate_trajectory",
    "initial_condition_grid",
    "infer_ordered_transition_bracket",
    "infer_return_map_branches",
    "infer_return_map_branches_coverage_censored",
    "infer_return_map_branches_robust",
    "infer_lower_support_slope_robust",
    "integrate_flip_segment",
    "lyapunov_spectrum",
    "largest_lyapunov_two_trajectory",
    "lyapunov_block_estimates",
    "rossler_equilibria",
    "rossler_jacobian",
    "rossler_hessian_action",
    "rossler_rhs",
    "periodic_components",
    "ranked_recurrence_candidates",
    "select_low_score_with_neighbors",
    "run_scan",
    "scrambled_sobol_section_states",
    "section_return_map",
    "next_section_return",
    "refine_pim_segment",
    "refine_censor_aware_pim_segment",
    "sprinkler_survivors",
    "survivor_return_pairs",
    "verify_completed_tile",
    "verify_completed_aggregate",
    "legacy_rossler_section",
]
